var questions = [
    {"id":1 ,"q":"1a. Corps de couleur brune\n\n1b. Corps d’une autre couleur","a":2,"b":13, "p":1},
    {"id":2 ,"q":"2a. Présence de poils sur le corps\n\n2b. Absence de poils","a":3,"b":8, "p":1},
    {"id":3 ,"q":"3a. Présence de mâchoire ou de palpe à l’avant de la tête \n\n3b. Absence de mâchoire ou de palpe","a":4,"b":5, "p":2},
    {"id":4 ,"q":"4a. Présence de palpe uniquement\n\n4b. Présence des deux membres","a":"Tigre d'eau","b":"Hétérocère bordé", "p":3},
    {"id":5 ,"q":"5a. Longueur des pattes antérieures plus courte que les autres pattes\n\n5b. Longueur des pattes antérieures égales à ou plus longues que les autres pattes", "a":"Dyptique déprédateur","b":6, "p":3},
    {"id":6 ,"q":"6a. Direction des antennes pointant vers l‘avant\n\n6b. Direction des antennes pointant vers l’arrière","a":"Stégobie des pharmacies","b":7, "p":5},
    {"id":7 ,"q":"7a. Abdomen ayant une forme rectangulaire\n\n7b. Abdomen ayant une forme circulaire","a":"Ernobius conicula","b":"Ptine bigarré", "p":6},
    {"id":8 ,"q":"8a. Forme des antennes courbée\n\n8b. Forme des antennes angulaire","a":9,"b":12, "p":2},
    {"id":9 ,"q":"9a. Présence de points noires sur les élytres\n\n9b. Absence de taches circulaires sur les élytres","a":"Coléoptère aquatique rampant Chaliplus","b":10, "p":8},
    {"id":10 ,"q":"10a. Présence de deux lignes noires horizontales sur chaque élytre\n\n10b. Absence de motif sur les élytres","a":"Coléo fort","b":11, "p":9},
    {"id":11 ,"q":"11a. Longueur des pattes antérieures plus courte que celle des pattes postérieures\n\n11b. Longueur des pattes antérieures égales à celle des pattes postérieures","a":"Agrile du framboisier","b":"Bupreste du pommier", "p":10},
    {"id":12 ,"q":"12a. Présence d’une mâchoire\n\n12b. Absence de mâchoire","a":"Charonçon du comcombre","b":"Perceur du pêcher", "p":8},
    {"id":13 ,"q":"13a. Corps d’une couleur rouge\n\n13b. Corps d’une autre couleur","a":"Tribolium rouge de la farine","b":14, "p":1},
    {"id":14 ,"q":"14a. Corps blanc avec taches noires sur le pronotum et les élytres\n\n14b. Corps de couleur noire","a":"Coléoptère blindé haldemani de nodulus de zéphorus","b": 15, "p":13},
    {"id":15 ,"q":"15a. Longueur des tarses postérieures plus longue que celle des fémurs postérieurs\n\n15b. Longueur des tarses postérieures plus petite que celle des fémurs postérieurs","a":16,"b":17, "p":14},
    {"id":16 ,"q":"16a. Présence d’une paire de palpes labiales\n\n16b. Absence de mâchoire et de palpes","a":"Ténébrion olifant","b":"Clairon des fourmis", "p":15},
    {"id":17 ,"q":"17a. Longueur des pattes postérieures plus longue que celle des pattes médianes\n\n17b. Longueur des pattes postérieure égale à celle des pattes médianes","a":"Gyrin","b":"Faux ver fil-de-fer", "p":15}
];
var coleopteres = [
    {"nom": "Tigre d'eau", "desc":null ,            "lien":"https://fr.wikipedia.org/wiki/Dytique"},
    {"nom": "Hétérocère bordé", "desc":null  ,      "lien":"https://fr.wikipedia.org/wiki/Coleoptera"},
    {"nom": "Dyptique déprédateur", "desc":null  ,  "lien":"https://fr.wikipedia.org/wiki/Dytique"},
    {"nom": "Stégobie des pharmacies", "desc":null, "lien":"https://fr.wikipedia.org/wiki/Stegobium_paniceum"},
    {"nom": "Ernobius conicula", "desc":null ,      "lien":"https://fr.wikipedia.org/wiki/Coleoptera"},
    {"nom": "Ptine bigarré", "desc":null  ,         "lien":"https://fr.wikipedia.org/wiki/Ptinus_fur"},
    {"nom": "Coléoptère aquatique rampant Chaliplus", "desc":null  , "lien":"https://docbebitte.com/2020/02/08/des-coleopteres-aquatiques-rampants/"    },
    {"nom": "Coléo fort", "desc":null  ,            "lien":"https://fr.wikipedia.org/wiki/Coleoptera"},
    {"nom": "Agrile du framboisier", "desc":null  , "lien":"http://www.omafra.gov.on.ca/IPM/french/raspberries/insects/rednecked-caneborer.html"    },
    {"nom": "Bupreste du pommier", "desc":null  ,   "lien":"https://reseaupommier.irda.qc.ca/?p=12001"},
    {"nom": "Charonçon du comcombre", "desc":null  ,"lien":"https://fr.wikipedia.org/wiki/Charan%C3%A7on"},
    {"nom": "Perceur du pêcher", "desc":null  ,     "lien":"http://www.omafra.gov.on.ca/IPM/french/tender/insects/ptb.html"},
    {"nom": "Tribolium rouge de la farine", "desc":null  , "lien":"https://www.grainscanada.gc.ca/fr/qualite-grains/gestion/identification-insectes/insectes-ravageurs-primaires/tribolium-rouge-farine.html"    },
    {"nom": "coleoptere blindé haldemani de nodulus de zéphorus", "desc":null  , "lien":"https://en.wikipedia.org/wiki/Zopherus"},
    {"nom": "Ténébrion olifant", "desc":null  ,     "lien":"https://grainscanada.gc.ca/fr/qualite-grains/gestion/identification-insectes/insectes-ravageurs-secondaires/tenebrion-olifant.html"    },
    {"nom": "Clairon des fourmis", "desc":null  ,   "lien":"https://fr.wikipedia.org/wiki/Thanasimus_formicarius"},
    {"nom": "Gyrin", "desc":null  ,                 "lien":"https://fr.wikipedia.org/wiki/Gyrin"},
    {"nom": "Faux ver fil-de-fer", "desc":null  ,   "lien":"https://fr.wikipedia.org/wiki/Taupin_des_moissons"}
];
